In [1]:
pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/b9/c5/fc1b368f303087d20e8c9bf3d6ceb186263cfac0ade735cd938538bea839/pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata
  Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Obtaining dependency information for numpy>=1.26.0 from https://files.pythonhosted.org/packages/ab/ca/feab00bd44aa5fe1ad2c18f08b4d3bb92e26484b0b1d1443897809ed528c/numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata
  Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Obtaining dependency information for tzdata from https://files.pythonhosted.org/packages/ce/e4/dccd7f47c4b64213ac01ef921a1337ee6e30e8c6466046018326977efd95/tzdata-2026.2-py2.py3-none-any.whl.metadata
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB 435.7 kB/s eta 0:00:23
   ---------------------------------------- 0.1/9.8 MB 544.7 kB/s eta 0:00:18
   ---------------------------------------- 0.1/9.8 MB 655.4 kB/s eta 0:00:15
    --------------------------------------- 0.2/9.8 MB 876.1 kB/s eta 0:00:11
   - -------------------------------------- 0.3/9.8 MB 1.2 MB/s eta 0:00:08
   - -------------------------------------- 0.5/9.8 MB 1.6 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/9.8 MB 1.9 MB/s eta 0:00:05
   --- ------------------------------------ 0.9/9.8 MB 2.5 MB/s eta 0:00:04
   ---- ----------------------------------- 1.0/9.8 MB 2.4 MB/s eta 0:00:04
   ---- ----------------------------------- 1.2/9.8 MB 2.5 MB/s eta 0:00:04
   ----- ---------------------------------- 1.4/9.8 MB 2.6 MB/s eta 0:00:04
   ------ --------------------------------- 1.5/9.8 MB 2.7 MB/s eta 0:00:04
   ------- -------------------------------- 1.7/9.8 MB 2.8 MB/s eta 0:00:03
   ------- -------------------------------- 1.8/9.8 MB 2.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.0/9.8 MB 2.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.2/9.8 MB 3.0 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/9.8 MB 3.0 MB/s eta 0:00:03
   ----------- ---------------------------- 2.7/9.8 MB 3.2 MB/s eta 0:00:03
   ----------- ---------------------------- 2.8/9.8 MB 3.1 MB/s eta 0:00:03
   ------------ --------------------------- 3.0/9.8 MB 3.2 MB/s eta 0:00:03
   ------------- -------------------------- 3.2/9.8 MB 3.3 MB/s eta 0:00:02
   ------------- -------------------------- 3.4/9.8 MB 3.3 MB/s eta 0:00:02
   -------------- ------------------------- 3.6/9.8 MB 3.4 MB/s eta 0:00:02
   ---------------- ----------------------- 4.0/9.8 MB 3.5 MB/s eta 0:00:02
   ----------------- ---------------------- 4.3/9.8 MB 3.6 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.8 MB 3.7 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.8 MB 3.7 MB/s eta 0:00:02
   ------------------- -------------------- 4.9/9.8 MB 3.7 MB/s eta 0:00:02
   -------------------- ------------------- 5.1/9.8 MB 3.8 MB/s eta 0:00:02
   --------------------- ------------------ 5.3/9.8 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.8 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.8 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 5.7/9.8 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.8 MB 3.7 MB/s eta 0:00:02
   ------------------------- -------------- 6.2/9.8 MB 3.8 MB/s eta 0:00:01
   -------------------------- ------------- 6.4/9.8 MB 3.8 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.8 MB 3.8 MB/s eta 0:00:01
   ---------------------------- ----------- 6.9/9.8 MB 3.9 MB/s eta 0:00:01
   ---------------------------- ----------- 7.0/9.8 MB 3.9 MB/s eta 0:00:01
   ----------------------------- ---------- 7.2/9.8 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 7.5/9.8 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 7.7/9.8 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.8 MB 4.0 MB/s eta 0:00:01
   --------------------------------- ------ 8.2/9.8 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.8 MB 4.0 MB/s eta 0:00:01
   ----------------------------------- ---- 8.6/9.8 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 9.0/9.8 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 9.3/9.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  9.6/9.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 3.9 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.2/12.3 MB 6.3 MB/s eta 0:00:02
   - -------------------------------------- 0.5/12.3 MB 5.9 MB/s eta 0:00:03
   - -------------------------------------- 0.6/12.3 MB 5.5 MB/s eta 0:00:03
   -- ------------------------------------- 0.9/12.3 MB 5.8 MB/s eta 0:00:02
   --- ------------------------------------ 1.1/12.3 MB 5.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.3 MB 5.0 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/12.3 MB 5.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.3 MB 5.3 MB/s eta 0:00:02
   ------ --------------------------------- 2.0/12.3 MB 5.2 MB/s eta 0:00:02
   ------- -------------------------------- 2.2/12.3 MB 5.1 MB/s eta 0:00:02
   ------- -------------------------------- 2.3/12.3 MB 5.1 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.3 MB 4.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.7/12.3 MB 4.8 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.3 MB 4.7 MB/s eta 0:00:02
   --------- ------------------------------ 3.1/12.3 MB 4.7 MB/s eta 0:00:02
   ---------- ----------------------------- 3.2/12.3 MB 4.6 MB/s eta 0:00:02
   ---------- ----------------------------- 3.3/12.3 MB 4.4 MB/s eta 0:00:03
   ----------- ---------------------------- 3.5/12.3 MB 4.4 MB/s eta 0:00:03
   ------------ --------------------------- 3.7/12.3 MB 4.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.3 MB 4.3 MB/s eta 0:00:02
   ------------- -------------------------- 4.1/12.3 MB 4.4 MB/s eta 0:00:02
   -------------- ------------------------- 4.4/12.3 MB 4.4 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.3 MB 4.4 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.3 MB 4.4 MB/s eta 0:00:02
   ---------------- ----------------------- 5.0/12.3 MB 4.5 MB/s eta 0:00:02
   ----------------- ---------------------- 5.3/12.3 MB 4.5 MB/s eta 0:00:02
   ----------------- ---------------------- 5.4/12.3 MB 4.5 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.3 MB 4.4 MB/s eta 0:00:02
   ------------------ --------------------- 5.7/12.3 MB 4.4 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.3 MB 4.3 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.3 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 6.2/12.3 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.3 MB 4.4 MB/s eta 0:00:02
   -------------------- ------------------- 6.5/12.3 MB 4.3 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.3 MB 4.3 MB/s eta 0:00:02
   ---------------------- ----------------- 6.9/12.3 MB 4.3 MB/s eta 0:00:02
   ---------------------- ----------------- 7.0/12.3 MB 4.3 MB/s eta 0:00:02
   ----------------------- ---------------- 7.2/12.3 MB 4.3 MB/s eta 0:00:02
   ----------------------- ---------------- 7.4/12.3 MB 4.3 MB/s eta 0:00:02
   ------------------------ --------------- 7.5/12.3 MB 4.3 MB/s eta 0:00:02
   ------------------------ --------------- 7.7/12.3 MB 4.3 MB/s eta 0:00:02
   ------------------------- -------------- 8.0/12.3 MB 4.3 MB/s eta 0:00:02
   -------------------------- ------------- 8.3/12.3 MB 4.4 MB/s eta 0:00:01
   --------------------------- ------------ 8.5/12.3 MB 4.4 MB/s eta 0:00:01
   ---------------------------- ----------- 8.8/12.3 MB 4.4 MB/s eta 0:00:01
   ----------------------------- ---------- 9.0/12.3 MB 4.4 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 4.4 MB/s eta 0:00:01
   ------------------------------ --------- 9.5/12.3 MB 4.5 MB/s eta 0:00:01
   ------------------------------- -------- 9.6/12.3 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 9.9/12.3 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 4.4 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 4.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.3/12.3 MB 4.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.3/12.3 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 10.6/12.3 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 4.3 MB/s eta 0:00:01
   ----------------------------------- ---- 10.9/12.3 MB 4.3 MB/s eta 0:00:01
   ------------------------------------ --- 11.1/12.3 MB 4.3 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 4.3 MB/s eta 0:00:01
   ------------------------------------- -- 11.4/12.3 MB 4.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 4.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.7/12.3 MB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 11.9/12.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  12.0/12.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  12.2/12.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  12.2/12.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 3.8 MB/s eta 0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
   ---------------------------------------- 0.0/349.3 kB ? eta -:--:--
   --- ------------------------------------ 30.7/349.3 kB 1.4 MB/s eta 0:00:01
   ---- ---------------------------------- 41.0/349.3 kB 330.3 kB/s eta 0:00:01
   ----------------------------------- ---- 307.2/349.3 kB 3.2 MB/s eta 0:00:01
   ---------------------------------------  348.2/349.3 kB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 349.3/349.3 kB 1.8 MB/s eta 0:00:00
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.3 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

Creating Dataframes

In [3]:
#from dictionary
data={'name':['Alice','Bob'],'Age':[25,30]}
df=pd.DataFrame(data)

In [10]:
# From list of lists
Ist = [['Alice',25],['Bob',30]]
df1 = pd.DataFrame(Ist,columns=['name','Age'])

Inspecting  Data

In [11]:
df.head() # First 5 rows
df.tail() # Last 5 rows
df.info() # Info about DataFrame
df.describe() # Summary statistics

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

Selecting data

In [ ]:
# Column selection
df['name'] 
df[['name','Age']]

In [23]:
# Row selection by label and position

df.loc[0]
df.iloc[1]

name    Bob
Age      30
Name: 1, dtype: object

Filtering Data

In [24]:
df[df['Age'] > 25] # Filter rows where Age > 25

  name  Age
1  Bob   30

Adding/Removing Columns

In [ ]:
df['Gender'] = ['F','M'] # Add new column
df.drop('Age', axis=1, inplace=True) # Remove column

Handling missing Data

In [26]:
df.isnull()
df.dropna()
df.fillna(0)

    name gender
0  Alice      F
1    Bob      M

Grouping and Aggregating

In [ ]:
df.groupby('gender')['Age'].mean()

Merging & Joining

In [ ]:
# merge two Dataframes
pd.merge(df1, df2, on='key')

In [ ]:
# join by index
df1.join(df2)

Reading/Writing Files

In [ ]:
# Read CSV
df = pd.read_csv('data.csv')

In [ ]:
# write CSV
df.to_csv

Useful Functions

In [ ]:
df.sort_values('Age')
df['Age'].apply(lambda x: x + 1)
df['Name'].unique()
df['Age'].value_counts()